### ISSUE TITLE
Support PR comment on 'push' events

### ISSUE THREAD

**Issue by cviddy** [ctrf-io/github-test-reporter#100]
We have a CI workflow where we only run our automated tests once a PR is created, but we still run all the other steps (build, publish, lint, etc) in our ci.yml file on push events. So this causes conflicts with the PR comment because it strictly only allows for `pull_request` events vs `push` events. So we are hoping there could be a way for there to be an input for PR number to be added manually so that it can post comments on non-pull_request events. 

So for example, in our CI file we have an if statement on when to run tests `if: ${{ github.event_name == 'pull_request' || needs.check-for-PR.outputs.pr_true == 'true' }}` this `check-for-PR` step will also provide a PR number if the check is true. 

I believe we could add a new input for `pr-number` and add an additional OR check in this block here to allow for it via the action package or via an input: https://github.com/ctrf-io/github-test-reporter/blob/0ed5a5d924efb01d9e42faa93acaf9bc7f4c054c/src/github/helpers.ts#L51
or maybe somewhere within this function? 
https://github.com/ctrf-io/github-test-reporter/blob/0ed5a5d924efb01d9e42faa93acaf9bc7f4c054c/src/github/handler.ts#L62

**Comment by Ma11hewThomas** [comment]
I like this idea! I think we can extend it to any issue if a number is provided. For example, we could add a new issue input that accepts an issue number, after all pull requests are issues with additional functionality. If specified, the reporter will post a comment on that issue, whether it's a PR or a regular issue. 

There is already the summary and pull_request (tied to the current workflow) input so I think it would work nicely. 

Something like - 

```yaml
# Behavior Options
    summary: true # Post report to the job summary. Default is true
    pull-request: false # Comment on pull request with report. Default is false
    issue: '' # Issue number to comment on, can also be a pull request number.
```

Would this work for your needs?
