### ISSUE TITLE
Report options not working when using "issue"

### ISSUE THREAD

**Issue by farid-zare** [ctrf-io/github-test-reporter#114]
Hi, thanks a million for your update on fork PRs.
I am using test reporter to make a comment on a pull request using issue number. 

This is the current setup that I am using:
 
**- name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1.0.5
        with:
          report-path: 'artifacts/ctrf-report.json'
          community-report-name: 'summary-short'
          test-report: false
          test-list-report: false
          flaky-report: false
          skipped-report: false
          issue: ${{ env.PR_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}**

However the output is very long with all the test results at the moment, how can I just keep the summary and failed tests and remove the rest?
It looks like options are not working when using "issue".

![Image](https://github.com/user-attachments/assets/5fd8ef3f-146e-49c8-b828-bd43fcddd8c0)

**Comment by Ma11hewThomas** [comment]
You're welcome! 

This should work - 

```yaml
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1.0.5
        with:
          report-path: 'artifacts/ctrf-report.json'          
          summary-report: true
          failed-report: true
          issue: ${{ env.PR_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

or community report:

```yaml
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1.0.5
        with:
          report-path: 'artifacts/ctrf-report.json'          
          community-report: true
          community-report-name: 'summary-short'
          issue: ${{ env.PR_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1.0.5
        with:
          report-path: 'artifacts/ctrf-report.json'          
          failed-report: true
          issue: ${{ env.PR_NUMBER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

(I haven't found a clean way for the user to set the order yet, so best to separate these two)
