### ISSUE TITLE
Creates a new comment after updating an existing comment once

### ISSUE THREAD

**Issue by koiralakiran1** [ctrf-io/github-test-reporter#121]
**Here's what my workflow looks like:**
```yaml
- name: Publish Test Report
  uses: ctrf-io/github-test-reporter@v1
  with:
    report-path: './ctrf/*.json'
    pull-request-report: true
    overwrite-comment: true
    comment-tag: "github-test-report"
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  if: always()
```

**Here's what happens:**
1. It adds a comment (C1) on the first run
2. It updates the comment (C1) on a second run (when I push a commit for eg)
3. It adds a new comment (C2) on a third run
4. It updates the new comment (C2) on a fourth run
and so on...

**Here's what I've found about the cause of the issue:**
In this function, when there is an existing comment, we don't add a marker (Line 129-135)
https://github.com/ctrf-io/github-test-reporter/blob/d112d190f748147504bf5100f49bbd0ff2fcdc68/src/github/handler.ts#L106-L151

I can create a PR with the fix if this is a valid bug.
