### ISSUE TITLE
Unable to create the required custom report — Only Partial Report Displayed

### ISSUE THREAD

**Issue by lytvynanton08** [ctrf-io/github-test-reporter#124]
Hi there,

I'm currently facing an issue while trying to generate a custom report using the ctrf-io/github-test-reporter@v1 action. I have followed the instructions for customizing the report template, but when I try to generate the report, I can only see a partial report. Specifically, I only see the summary with the number of tests, passed, failed, flaky, and skipped tests, but the detailed test information (such as the individual test results) does not display as expected.

I have created a custom Handlebars template for the report and provided the correct paths for both the report JSON and the template. Here's the snippet of the relevant part of my configuration:

```
- name: Publish Test Report
  uses: ctrf-io/github-test-reporter@v1
  with:
    report-path: './path/to/merged-ctrf-report.json'
    template-path: './path/to/custom-ctrf-report.hbs'
    custom-report: true
  if: success() || failure()
  continue-on-error: true
```

I had an idea to extend the report (dist/reports/suite-folded.hbs) by showing "flaky" instead of "other" and, in case a test fails, adding a dropdown under the failed test with the error message (something similar like in dist/reports/suite-folded.hbs)

Could you please assist me in troubleshooting this issue? Perhaps I'm doing something incorrectly, or there’s a limitation preventing this, or I might be missing a configuration that’s required for the full report to be generated. I do not see any errors during the processing of the report on CI, so it's unclear what might be causing the issue.

Here’s my custom template:
```
### Summary
| **Tests 📝** | **Passed ✅** | **Failed ❌** | **Flaky 🍂** | **Skipped ⏭️** |
| --- | --- | --- | --- | --- |
| {{ctrf.summary.tests}} | {{ctrf.summary.passed}} | {{ctrf.summary.failed}} | {{countFlaky ctrf.tests}} | {{ctrf.summary.skipped}} |

### Details
<table>
  <thead>
    <tr>
      <th>Suite</th>
      <th>Passed</th>
      <th>Failed</th>
      <th>Flaky</th>
      <th>Duration</th>
    </tr>
  </thead>
  <tbody>
    {{#each ctrf.extra.suites}}
    <tr>
      <td>
        <details>
          <summary>{{getCtrfEmoji this.results.summary.extra.result}} {{this.results.extra.groupKey}}</summary>
          {{#each this.results.tests}}
              {{#if flaky}}
                <div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{getCtrfEmoji "flaky"}} {{this.name}} </div>
              {{else}}
                {{#if (eq this.status "failed")}}
                  <details>
                    <summary>{{getCtrfEmoji "failed"}} {{this.name}}</summary>
                    <pre><code>{{#if this.message}}{{formatMessagePreCode this.message true}}{{else}}No message available{{/if}}</code></pre>
                  </details>
                {{else}}
                  <div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{getCtrfEmoji this.status}} {{this.name}} </div>
                {{/if}}
              {{/if}}
          {{/each}}
        </details>
      </td>
      <td>{{getCtrfEmoji "passed"}} {{this.results.summary.passed}}</td>
      <td>{{getCtrfEmoji "failed"}} {{this.results.summary.failed}}</td>
      <td>
        {{#if flaky}}
          {{getCtrfEmoji "flaky"}}
        {{else}}
        {{/if}}
      </td>
      <td>{{formatDuration 0 this.results.summary.extra.duration}}</td>
    </tr>
    {{/each}}
  </tbody>
</table>

```

And only this part of a template I see on ci:
```
### Summary
| **Tests 📝** | **Passed ✅** | **Failed ❌** | **Flaky 🍂** | **Skipped ⏭️** |
| --- | --- | --- | --- | --- |
| {{ctrf.summary.tests}} | {{ctrf.summary.passed}} | {{ctrf.summary.failed}} | {{countFlaky ctrf.tests}} | {{ctrf.summary.skipped}} |

### Details
<table>
  <thead>
    <tr>
      <th>Suite</th>
      <th>Passed</th>
      <th>Failed</th>
      <th>Flaky</th>
      <th>Duration</th>
    </tr>
```

I would greatly appreciate any help or advice you could provide.

Thank you for your help!

**Comment by Ma11hewThomas** [comment]
The problem is that by default, the reporter doesn't group by suite unless you choose one of the suite reports, but you can force the grouping by using `always-group-by` input. 

```yaml
- name: Publish Test Report
  uses: ctrf-io/github-test-reporter@v1
  with:
    report-path: './path/to/merged-ctrf-report.json'
    template-path: './path/to/custom-ctrf-report.hbs'
    custom-report: true
    always-group-by: true
    group-by: 'suite'
  if: success() || failure()
  continue-on-error: true
```

That should result in a report like this - 

https://github.com/ctrf-io/github-test-reporter/actions/runs/13550537476/attempts/1#summary-37872853112

As you can see there is some styling to figure out! 

Thanks
