### ISSUE TITLE
Insights and Slowest Tests Reports Not Displaying Data

### ISSUE THREAD

**Issue by gdavidkov** [ctrf-io/github-test-reporter#127]
Hello,
First of all, I want to say that github-test-reporter is an amazing tool and has been incredibly helpful in improving our test reporting workflow. Thank you for building and maintaining it! 🚀

However, I noticed that the Insights and Slowest Tests sections are not displaying any data. The Slowest Test (p95) field is showing "NaNmNaNs," and no tests appear under Slowest Tests, even though my test suite ran successfully.

![Image](https://github.com/user-attachments/assets/f6ef8fed-7b89-4f64-b09d-c5deaf63d8e9)

```yaml
- name: Publish Test Report
  uses: ctrf-io/github-test-reporter@v1
  with:
    report-path: './reports/**/*.json'
    write-ctrf-to-file: './reports/ctrf-report.json'
    annotate: false
    previous-results-report: true
    flaky-report: true
    insights-report: true
    slowest-report: true
    exit-on-fail: true
    summary-report: true
    group-by: 'suite'
    use-suite-name: true
    failed-report: true
    pull-request: true
    upload-artifact: true
```
Am I missing a configuration step to enable these reports?
