### ISSUE TITLE
Distinction between `update-comment` and `overwrite-comment`

### ISSUE THREAD

**Issue by batrdn** [ctrf-io/github-test-reporter#149]
I'm really confused about the difference between `update-comment` and `overwrite-comment`. Currently, I have the action running in a monorepo, where tests run in parallel. For example:

```yaml
jobs:
    app1:
        - name: Run tests
           run: npm run test
        - name: Publish Test Report
           uses: ctrf-io/github-test-reporter@v1
           with:
               pull-request: true
               update-comment: true
               # overwrite-comment: true
               summary-report: true
    app2:
        # Same thing
```

Now, with only `update-comment` set to true, test report comments are added in the pr for each apps -- expected result. If I rerun the actions again, new comments are added -- I'd expected that the previous comments would be updated.

If enable only `overwrite-comment` (update-comment is set to false), then it updates the previous comment, which is nice, but it overwrites all the other comments of the parallel actions, i.e,. if app2 finishes last, then only the test report of app2 is displayed in the PR.

What would be the ideal way to configure this action in a monorepo setting?

**Comment by Ma11hewThomas** [comment]
Using `comment-tag` should work for this use case - 

```yaml
jobs:
    app1:
        - name: Run tests
           run: npm run test
        - name: Publish Test Report
           uses: ctrf-io/github-test-reporter@v1
           with:
               pull-request: true
               update-comment: true
               # overwrite-comment: true
               summary-report: true
               comment-tag: app1
    app2:
        # Same thing
        comment-tag: app2
```

More info here - https://github.com/ctrf-io/github-test-reporter?tab=readme-ov-file#comment-management-inputs

Let me know how it goes
