### ISSUE TITLE
Documentation improvement for JUnit to CTRF Integration

### ISSUE THREAD

**Issue by kpopovic** [ctrf-io/github-test-reporter#150]
Hello,

I would recommend to improve documentation when JUnit is used. It is missleading.
[JUnit to CTRF Integration](https://github.com/ctrf-io/github-test-reporter/blob/main/docs/integrations.md#junit-to-ctrf-integration)

instead of: report-path: './ctrf/*.json'
to be: report-path: 'target/surefire-reports/*.xml'

```yaml
- name: Publish Test Report
  uses: ctrf-io/github-test-reporter@v1
  with:
    report-path: 'target/surefire-reports/*.xml'
    integrations-config: |
      {
        "junit-to-ctrf": {
          "enabled": true,
          "action": "convert",
          "options": {
            "output": "./ctrf-reports/ctrf-report.json",
            "toolname": "junit-to-ctrf",
            "useSuiteName": false,
            "env": {
              "appName": "my-app"
            }
          }
        }
      }
  if: always()
```
