### ISSUE TITLE
Bug: status-check behavior

### ISSUE THREAD

**Issue by JulianHBuecher** [ctrf-io/github-test-reporter#155]
Hi, I'm facing an interesting behaviour using the `status-check` option. Maybe I didn't really understand its purpose, but afterwards is my configuration:

```yaml
...
      - name: Publish test report
        uses: ctrf-io/github-test-reporter@v1
        if: always()
        with:
          report-path: "gen/tmp/unittests-*.xml"
          summary-report: true
          insights-report: true
          pull-request-report: true
          status-check: true
          status-check-name: 'Julians Check'
          comment-tag: '${{ github.workflow }}-${{ github.job }}'
          write-ctrf-to-file: ${{ env.CTRF_PROCESSED_REPORT }}
          title: 'Test Report - Custom Domains'
          integrations-config: |
            {
              "junit-to-ctrf": {
                "enabled": true,
                "action": "convert",
                "options": {
                  "output": "${{ env.CTRF_REPORT_FILE }}",
                  "toolname": "junit-to-ctrf",
                  "useSuiteName": false,
                  "env": {
                    "appName": "..."
                  }
                }
              }
            }
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Problem**: Using this step configured as above, the following behaviour occurs during a test run with...
- test errors: The status check appears as "failed" in my PR validation and the other two checks (which run before this one) I'm running reset from "Successful" to "Expected" state.
- test success: The status check appears as "Expected" in the PR validation and does not update.

Is the described behaviour expected? Or did I misconfigured the step?
